version: '3'

services:
         dsi-runtime:
                 image: dsi-runtime
                 ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
         dsi-runtime-openjdk:
                 image: dsi-runtime-openjdk
                 ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
         dsi-runtime-ibmjava:
                 image: dsi-runtime-ibmjava
                 ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
