version: '3'

services:
        dsi-runtime:
                image: dsi-runtime
                ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
                command: ["/root/start.sh", $DSI_TEMPLATE]
                environment:
                        - LOGGING_TRACE_SPECIFICATION=$LOGGING_TRACE_SPECIFICATION
                volumes:
                        - volume-templates:/opt/dsi/runtime/wlp/templates/servers

        dsi-runtime-openjdk:
                image: dsi-runtime-openjdk
                ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
                command: ["/root/start.sh", $DSI_TEMPLATE]
                environment:
                        - LOGGING_TRACE_SPECIFICATION=$LOGGING_TRACE_SPECIFICATION
                volumes:
                        - volume-templates:/opt/dsi/runtime/wlp/templates/servers

        dsi-runtime-ibmjava:
                image: dsi-runtime-ibmjava
                ports:
                        - "${HTTP_PORT}:9080"
                        - "${HTTPS_PORT}:9443"
                command: ["/root/start.sh", $DSI_TEMPLATE]
                environment:
                        - LOGGING_TRACE_SPECIFICATION=$LOGGING_TRACE_SPECIFICATION
                volumes:
                        - volume-templates:/opt/dsi/runtime/wlp/templates/servers

volumes:
        volume-templates:
